#How to compile execubtable to Add data to database
g++ read_conductivity.cpp conductivity_database.cpp -o condToDatabase -I/usr/include/mysql -lmysqlclient

# Compile to just read conductivity from sensor
g++ read_conductivity.cpp conductivity_read_exe.cpp -o condRead
